### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by akhilalexander** [OmkarPathak/ResumeParser#6]
@OmkarPathak  When I run the cli.py, I encountered with this error

Traceback (most recent call last):
  File "cli.py", line 6, in <module>
    from resume_parser.resume_parser import ResumeParser
  File "/home/AnacondaProjects/jupyter/Pdf_Extractor/ResumeParser-master/resume_parser/resume_parser.py", line 4, in <module>
    from . import utils
  File "/home/AnacondaProjects/jupyter/Pdf_Extractor/ResumeParser-master/resume_parser/utils.py", line 10, in <module>
    from . import constants as cs
  File "/home/AnacondaProjects/jupyter/Pdf_Extractor/ResumeParser-master/resume_parser/constants.py", line 201
SyntaxError: Non-ASCII character '\xc2' in file /home/AnacondaProjects/jupyter/Pdf_Extractor/ResumeParser-master/resume_parser/constants.py on line 201, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Im using Ubuntu 16.04, Python 2.7

**Comment by OmkarPathak** [comment]
@akhilalexander check [this](https://stackoverflow.com/a/18078860). This seems to solve your problem

**Comment by akhilalexander** [comment]
@OmkarPathak  I got it correct when I removed the space in fundraised and reduced annual expenses
MEASURABLE_RESULTS = {
    'metrics': [
                'fundraised',
          ]      'reduced annual expenses'

**Comment by OmkarPathak** [comment]
@akhilalexander Glad. Closing this issue 😄
